# Auto-generated DAG for Workflow: ml_pipeline_test
# Workflow ID: 308a3ac8-3e2c-41cd-9b51-4b25d8a25173
# Generated by MLOps Workflow System

from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.docker.operators.docker import DockerOperator
from datetime import datetime, timedelta

# DAG default arguments
default_args = {
    'owner': 'mlops',
    'depends_on_past': False,
    'start_date': datetime(2024, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 0,
}

# Create DAG
with DAG(
    dag_id='workflow_308a3ac8-3e2c-41cd-9b51-4b25d8a25173',
    default_args=default_args,
    description='ML Pipeline using Git repository functions',
    schedule_interval='@daily',
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=['mlops', 'auto-generated', 'ml_pipeline_test']
) as dag:


    # Task: evaluate_model

    # Git-based task: executes Python function from Git repository in Docker
    evaluate_model = DockerOperator(
        task_id='evaluate_model',
        image='python:3.9-slim',
        api_version='auto',
        auto_remove=True,
        command=[
            'sh', '-c',
            '''
            set -e
            echo "=== Installing git ==="
            apt-get update -qq && apt-get install -y -qq git > /dev/null 2>&1

            echo "=== Cloning Git repository ==="
            git clone --depth 1 --branch main https://github.com/gjgj4869/mlops-workflow-test.git /workspace
            cd /workspace

            echo "=== Repository cloned successfully ==="
            ls -la

            

            echo "=== Executing Python function ==="
            python3 -c "
import sys
sys.path.insert(0, '/workspace')

# Import function from script
from src.train import evaluate_model

# Execute function
print('Calling evaluate_model...')
result = evaluate_model()
print(f'Result: {result}')
            "

            echo "=== Task completed successfully ==="
            '''
        ],
        docker_url='unix://var/run/docker.sock',
        network_mode='bridge',
        mount_tmp_dir=False,
        retries=1,
        retry_delay=timedelta(seconds=300),
    )




    # Task: load_data

    # Git-based task: executes Python function from Git repository in Docker
    load_data = DockerOperator(
        task_id='load_data',
        image='python:3.9-slim',
        api_version='auto',
        auto_remove=True,
        command=[
            'sh', '-c',
            '''
            set -e
            echo "=== Installing git ==="
            apt-get update -qq && apt-get install -y -qq git > /dev/null 2>&1

            echo "=== Cloning Git repository ==="
            git clone --depth 1 --branch main https://github.com/gjgj4869/mlops-workflow-test.git /workspace
            cd /workspace

            echo "=== Repository cloned successfully ==="
            ls -la

            

            echo "=== Executing Python function ==="
            python3 -c "
import sys
sys.path.insert(0, '/workspace')

# Import function from script
from src.data import load_data

# Execute function
print('Calling load_data...')
result = load_data()
print(f'Result: {result}')
            "

            echo "=== Task completed successfully ==="
            '''
        ],
        docker_url='unix://var/run/docker.sock',
        network_mode='bridge',
        mount_tmp_dir=False,
        retries=2,
        retry_delay=timedelta(seconds=300),
    )




    # Task: train_model

    # Git-based task: executes Python function from Git repository in Docker
    train_model = DockerOperator(
        task_id='train_model',
        image='python:3.9-slim',
        api_version='auto',
        auto_remove=True,
        command=[
            'sh', '-c',
            '''
            set -e
            echo "=== Installing git ==="
            apt-get update -qq && apt-get install -y -qq git > /dev/null 2>&1

            echo "=== Cloning Git repository ==="
            git clone --depth 1 --branch main https://github.com/gjgj4869/mlops-workflow-test.git /workspace
            cd /workspace

            echo "=== Repository cloned successfully ==="
            ls -la

            

            echo "=== Executing Python function ==="
            python3 -c "
import sys
sys.path.insert(0, '/workspace')

# Import function from script
from src.train import train_model

# Execute function
print('Calling train_model...')
result = train_model()
print(f'Result: {result}')
            "

            echo "=== Task completed successfully ==="
            '''
        ],
        docker_url='unix://var/run/docker.sock',
        network_mode='bridge',
        mount_tmp_dir=False,
        retries=2,
        retry_delay=timedelta(seconds=600),
    )





    # Task Dependencies



    train_model >> evaluate_model







    load_data >> train_model


