# Auto-generated DAG for Workflow: test_git_sha
# Workflow ID: 7eb5d169-3bb7-4947-a741-4d1c5a56979c
# Generated by MLOps Workflow System

from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.docker.operators.docker import DockerOperator
from datetime import datetime, timedelta

# DAG default arguments
default_args = {
    'owner': 'mlops',
    'depends_on_past': False,
    'start_date': datetime(2024, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 0,
}

# Create DAG
with DAG(
    dag_id='workflow_7eb5d169-3bb7-4947-a741-4d1c5a56979c',
    default_args=default_args,
    description='Testing git SHA',
    schedule_interval='@once',
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=['mlops', 'auto-generated', 'test_git_sha']
) as dag:


    # Task: load_data_with_sha

    # Git-based task: executes Python function from Git repository in Docker
    load_data_with_sha = DockerOperator(
        task_id='load_data_with_sha',
        image='python:3.9-slim',
        api_version='auto',
        auto_remove=True,
        command=[
            'sh', '-c',
            '''
            set -e
            echo "=== Installing git ==="
            apt-get update -qq && apt-get install -y -qq git > /dev/null 2>&1

            echo "=== Cloning Git repository ==="
            
            # Specific commit SHA provided - clone and checkout that commit
            git clone https://github.com/gjgj4869/mlops-workflow-test.git /workspace
            cd /workspace
            git checkout b680f1b2af2c58a4184e6ad190bb52668fafe7fb
            echo "Checked out commit: b680f1b2af2c58a4184e6ad190bb52668fafe7fb"
            

            echo "=== Repository cloned successfully ==="
            ls -la

            

            echo "=== Executing Python function ==="
            python3 -c "
import sys
sys.path.insert(0, '/workspace')

# Import function from script
from src.data import load_data

# Execute function
print('Calling load_data...')
result = load_data()
print(f'Result: {result}')
            "

            echo "=== Task completed successfully ==="
            '''
        ],
        docker_url='unix://var/run/docker.sock',
        network_mode='bridge',
        mount_tmp_dir=False,
        retries=2,
        retry_delay=timedelta(seconds=300),
    )





    # Task Dependencies


