# Auto-generated DAG for Workflow: ml_pipeline_example
# Workflow ID: 92ab1a96-b87b-4f50-95a0-5fe46c172040
# Generated by MLOps Workflow System

from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime, timedelta

# DAG default arguments
default_args = {
    'owner': 'mlops',
    'depends_on_past': False,
    'start_date': datetime(2024, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 0,
}

# Create DAG
with DAG(
    dag_id='workflow_92ab1a96-b87b-4f50-95a0-5fe46c172040',
    default_args=default_args,
    description='Example ML Pipeline - Data preprocessing and model training',
    schedule_interval='@daily',
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=['mlops', 'auto-generated', 'ml_pipeline_example']
) as dag:


    # Task: data_preprocessing
    def data_preprocessing_func(**context):
        """
        Auto-generated task function for: data_preprocessing
        """
        # User-defined Python code
        import pandas as pd
        print("Data preprocessing started")
        data = {"col1": [1, 2, 3], "col2": [4, 5, 6]}
        df = pd.DataFrame(data)
        print(f"Data shape: {df.shape}")
        context["ti"].xcom_push(key="data_shape", value=str(df.shape))
        print("Data preprocessing completed")

    data_preprocessing = PythonOperator(
        task_id='data_preprocessing',
        python_callable=data_preprocessing_func,
        op_kwargs={},
        retries=2,
        retry_delay=timedelta(seconds=300),
        provide_context=True,
    )

    # Task: model_training
    def model_training_func(**context):
        """
        Auto-generated task function for: model_training
        """
        # User-defined Python code
        from sklearn.linear_model import LinearRegression
        import numpy as np
        print("Model training started")
        data_shape = context["ti"].xcom_pull(task_ids="data_preprocessing", key="data_shape")
        print(f"Data shape from preprocessing: {data_shape}")
        X = np.array([[1], [2], [3]])
        y = np.array([2, 4, 6])
        model = LinearRegression()
        model.fit(X, y)
        print(f"Model trained. Coefficient: {model.coef_[0]}")
        context["ti"].xcom_push(key="model_coef", value=float(model.coef_[0]))
        print("Model training completed")

    model_training = PythonOperator(
        task_id='model_training',
        python_callable=model_training_func,
        op_kwargs={},
        retries=2,
        retry_delay=timedelta(seconds=300),
        provide_context=True,
    )


    # Task Dependencies





    data_preprocessing >> model_training


